<?php
/* @var Mage4\ImageComparisonSlider\Block\Slider\Slider $block */

?>


<?php //echo $block->getSlider()->getComparisonDirection(); ?>

<div id="test"></div>
<!--<div class="test slider"></div>-->

<script>
    require(['jquery', 'beforeEffectslider'], function($, beforeEffectslider) {
        beforeEffectslider({
            Selector: "#test", // Element that the slider will be build in
            Vertical: <?php echo $block->getSlider()->getComparisonDirection(); ?>, // this Slider is Vertical! (false is default value)
            BeforeImage: <?php echo $block->getSlider()->getBeforeDesktopImage(); ?>,
            // Before Image
            BeforeAlt: "Before_image", // Before Image Alt
            AfterImage: <?php echo $block->getSlider()->getAfterDesktopImage(); ?>, // After Image
            ImageURL: <?php echo $block->getStoreMediaPathUrl(''); ?>, // Image url
            AftereAlt: "After_image", // After Image Alt
            DragFrom: <?php echo $block->getSlider()->getDragFrom(); ?>, // Percent % of before Image
            MaxDrag: <?php echo $block->getSlider()->getMaxDrag(); ?>, //Max drag from right or bottom if vertical
            MinDrag: <?php echo $block->getSlider()->getMinDrag(); ?>, //Min drag from left or top if vertical
            DragIcon: <?php echo $block->getSlider()->getDragIcon(); ?>, //no html, only codes
            IconSize: <?php echo $block->getSlider()->getIconSize(); ?>, //Icon size
            IconColor: <?php echo $block->getSlider()->getIconColor(); ?>, //Icon Color
            LineColor: <?php echo $block->getSlider()->getLineColor(); ?>, //Line Color
            ButtonGradient: ["#13B135", "red"], // Line Button gradient (keep same color for no gradient)
            ButtonBorder: "none", //Line Button Border Color
            ButtonRaduis: <?php echo $block->getSlider()->getButtonRadius(); ?>, // Line Button Raduis
            Cursor: <?php echo $block->getSlider()->getCursor(); ?>, // Cursor style on button hover, for more: https://developer.mozilla.org/fr/docs/Web/CSS/cursor
            Buttons: <?php echo $block->getSlider()->getButtons(); ?>, // Show before and after buttons ?
            ButtonsText: {
                //After Before Buttons Texts
                after: <?php echo $block->getSlider()->getButtonsTextAfter(); ?>,
                before: <?php echo $block->getSlider()->getButtonsTextBefore(); ?>,
            },
            Border: {
                // Border properties
                color: "black",
                width: 0, // 0 for no border
                style: "none",
            },
            //   callbackBefore: () => alert("before build"), //Callback Before building slider
            //   callbackAfter: () => alert("after build"), //Callback After building slider
        });
    })
</script>
