<?php
/* @var Mage4\ImageComparisonSlider\Block\Slider\Slider $block */

?>
<style>
    .box {
        width: 50%;
        height: 100%
    }

    .center {
        display: flex;
        align-items: center;
        justify-content: center;
    }
</style>

<div id="ImageComprasion" class="center">
    <div id="beforeEffectslider" class="box"></div>
</div>

<script type="text/x-magento-init">
   {
   "#ImageComprasion": {
       "Mage4_ImageComparisonSlider/js/comparisionslider":{
        "Vertical": <?= $block->getSlider()->getComparisonDirection() ?? false ?>,
      "BeforeImage": "<?= $block->getStoreMediaPathUrl($block->getSlider()->getBeforeDesktopImage()); ?>",
      "BeforeImageMobile": "<?=$block->getStoreMediaPathUrl($block->getSlider()->getBeforeMobileImage()); ?>",
      "BeforeAlt": "<? $block->getSlider()->getBeforeDesktopImage(); ?>",
      "AfterImage": "<?= $block->getStoreMediaPathUrl($block->getSlider()->getAfterDesktopImage()); ?>",
      "AfterImageMobile": "<?= $block->getStoreMediaPathUrl($block->getSlider()->getAfterMobileImage()); ?>",
      "AftereAlt": "<?= $block->getSlider()->getAfterDesktopImage(); ?>",
      "DragFrom": <?= $block->getSlider()->getDragFrom() ?? 50 ?>,
      "MaxDrag": <?= $block->getSlider()->getMaxDrag() ?? 0 ?>,
      "MinDrag": <?= $block->getSlider()->getMinDrag() ?? 30 ?>,
      "DragIcon": "<?= $block->getSlider()->getDragIcon() ?? '↔' ?>",
      "IconSize": <?= $block->getSlider()->getIconSize() ?? '24' ?>,
      "IconColor": "<?= $block->getSlider()->getIconColor() ?? '#FFF' ?>",
      "LineColor": "<?= $block->getSlider()->getLineColor() ?? '#282828' ?>",
      "ButtonRaduis": <?= $block->getSlider()->getButtonRadius() ?? 50 ?>,
      "Cursor": "<?= $block->getSlider()->getCursor() ?? 'ew-resize' ?>",
      "Buttons": <?= $block->getSlider()->getButtons() ?? false ?>,
      "ButtonsText": {
         "after": "<?= $block->getSlider()->getButtonsTextAfter(); ?>",
         "before": "<?=  $block->getSlider()->getButtonsTextBefore(); ?>"
      }
       }
   }
}
